name: CI for build, style check, test, and javadoc generation

on:
  push:
    branches:
      - main
      - ali
  pull_request:
    branches:
      - main
      - ali

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 1.8

      - name: Change directory to project
        run: cd .\warzone\

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run Junit Tests
        run: mvn test

      - name: Check JavaDoc
        run: mvn checkstyle:checkstyle

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc