name: CI for build, style check, test, and javadoc generation

on:
  push:
    branches:
      - main
      - ali
  pull_request:
    branches:
      - main
      - ali

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Build with Maven
        run: |
          cd ./warzone/
          mvn -B clean verify   

      - name: Run Junit Tests
        run:  |
          cd ./warzone/
          mvn test

      - name: Check JavaDoc
        run:  |
          cd ./warzone/
          mvn checkstyle:checkstyle

      - name: Generate JavaDoc
        run:  |
          cd ./warzone/
          mvn javadoc:javadoc