

name: build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd .\Warzone\
        mvn clean install -DskipTests=true

    - name: run Test Cases
      run: |
        cd .\Warzone\
        mvn test
        
    - name: Check styling
      run: mvn checkstyle:checkstyle

    - name: Generate JavaDoc
      run: mvn javadoc:javadoc
        
        
